export const ENTER_COMMAND = 'ENTER_COMMAND';

export const CHANGE_PLAYER_NAME = 'CHANGE_PLAYER_NAME';
export const CHANGE_PLAYER_SPRITE = 'CHANGE_PLAYER_SPRITE';

export const TOGGLE_MUSIC = 'TOGGLE_MUSIC';
